[project]
name = "RasaVasp"
version = "0.1.0"
description = "RasaVasp"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "rasa==3.6.21",
]

[dependency-groups]
dev = ["basedpyright>=1.31.4", "ruff>=0.12.12"]
